### PR TITLE
Evaluation of LLMs using beyondllm

### PR DESCRIPTION
**Pull request by ritwickbhargav80**
Will keep on contributing to add support to more LLMs to this application.
**DEPLOYED PREVIEW:** https://quick-llm-model-evaluations.streamlit.app

**Current supported LLMs:**
- [X] Gemini
    - [X] gemini-1.0-pro
    - [X] gemini-pro
    - [X] gemini-1.5-pro-latest
- [X] OpenAI
    - [X] gpt-3.5-turbo
    - [X] gpt-4
    - [X] gpt-4-turbo
- [X] Azure OpenAI
    - [X] gpt-35-turbo
    - [X] gpt-4
    - [X] gpt-35-turbo-16k
- [X] Anthropic
    - [X] claude-3-5-sonnet-20240620
    - [X] claude-3-haiku-20240307
    - [X] claude-3-sonnet-20240229
    - [X] claude-3-opus-20240229

**P.S.:** Thanks @tarun-aiplanet and team for delivering the wonderful session. Had fun while working with `beyondllm` and RAG Challenge.🥳

### CODE REVIEW

**Comment by tarun-aiplanet** [comment]
Hi @ritwickbhargav80, will wait for the end of the bootcamp live sessions. Then based on the PRs we will merge it and send out the swags. 

Thanks for your PR. Happy learning!

**Comment by ritwickbhargav80** [comment]
<ins>**What's new in v1.1.0?**</ins>
- Added support to Groq, HuggingFace models as well.
- Added Simultaneous evaluations of LLM models in one click.

**DEPLOYED PREVIEW:** https://quick-llm-model-evaluations.streamlit.app

**Current supported LLMs:**
- [X] **Gemini**
    - [X] gemini-1.0-pro
    - [X] gemini-pro
    - [X] gemini-1.5-pro-latest
- [X] **OpenAI**
    - [X] gpt-3.5-turbo
    - [X] gpt-4
    - [X] gpt-4-turbo
    - [X] gpt-3.5-turbo-16k
- [X] **Azure OpenAI**
    - [X] gpt-35-turbo
    - [X] gpt-4
    - [X] gpt-35-turbo-16k
- [X] **Anthropic**
    - [X] claude-3-5-sonnet-20240620
    - [X] claude-3-haiku-20240307
    - [X] claude-3-sonnet-20240229
    - [X] claude-3-opus-20240229
- [X] **Groq**
    - [X] mixtral-8x7b-32768
    - [X] gemma2-9b-it
    - [X] llama-3.1-8b-instant
    - [X] llama3-70b-8192
    - [X] llama3-8b-8192
    - [X] llama3-groq-70b-8192-tool-use-preview
    - [X] llama3-groq-8b-8192-tool-use-preview
- [X] **Hugging Face**
    - [X] huggingfaceh4/zephyr-7b-alpha
    - [X] huggingfaceh4/zephyr-7b-beta

**Review by tarun-aiplanet — COMMENTED** [review]
need a readme file inside the directory to describe what the cookbook is about

**Comment by ritwickbhargav80** [comment]
> need a readme file inside the directory to describe what the cookbook is about

Added!✅

**Pull request merged**
