### PR TITLE
Add: WeaviateDB Support

### PR DESCRIPTION
**Pull request by Jai0401**
Added WeaviateDB vector store.

This pull request:

- progresses: #29

### CODE REVIEW

**Comment by Jai0401** [comment]
@tarun-aiplanet Can you review this PR?

**Review by tarun-aiplanet — COMMENTED** [review]
lgtm

**Comment by tarun-aiplanet** [comment]
There is a RAG challenge going on until next month. Do you want to participate?

You can add an example or cookbook using Weaviate and participate in the challenge. Top 3 examples/cookbook will get a swag delievered to them.

**Comment by Jai0401** [comment]
@tarun-aiplanet Sure, I would like to participate. I will add an example for Weaviate.

**Pull request merged**
